name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      #################### BUILD ####################
      - name: Make Static Files
        run: python3 tools/ssg/main.py -vf

      #################### VALIDATE ####################
      - name: W3 Validate HTML
        uses: anishathalye/proof-html@v2
        with:
          directory: ./public/
          enforce_https: false
          disable_external: true

      #################### UPLOAD ####################
      - name: Upload Pages Artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: public/

  Deploy:
    needs: Build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
