name: Minify Assets

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install deps
      - run: npm install clean-css-cli -g
      - run: npm install uglify-js -g
      - run: npm install html-minifier -g

      - name: Minify CSS
        run: |
          find . -type f -name "*.css" -not -path "*/node_modules/*" -exec cleancss -o {} {} \;

      - name: Minify js
        run: |
          find . -type f -name "*.js" -not -path "*/node_modules/*" -exec uglifyjs {} -o {} \;

      - name: Minify HTML
        run: |
          find . -type f -name "*.html" -not -path "*/node_modules/*" -exec html-minifier {} -o {} \
            --collapse-whitespace --html5 --remove-comments --minify-css --minify-js \;

      # Push to gh-pages branch
      - if: github.event_name != 'pull_request'
        run: |
          git config user.name "Travis Heavener"
          git config user.email "travis.heavener@gmail.com"
          git commit -am "Automated minification of ${{ github.sha }}"
          git push --force -u origin main:gh-pages
