name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  minify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    # install deps
    - run: npm install clean-css-cli -g
    - run: npm install uglify-js -g

    # minify in place
    - run: uglifyjs ./js/globals.js -o      ./js/globals.js
    - run: uglifyjs ./projects/index.js -o  ./projects/index.js

    - run: cleancss -o ./css/globals.css    ./css/globals.css
    - run: cleancss -o ./resume/index.css   ./resume/index.css
    - run: cleancss -o ./projects/index.css ./projects/index.css
    - run: cleancss -o ./bio/index.css      ./bio/index.css

    # push to gh-pages branch
    - run: |
        git config user.name "Travis Heavener"
        git config user.email "travis.heavener@gmail.com"
        git commit -am "Automated CSS/JS minification of ${{ github.sha }}"
        git push --force -u origin main:gh-pages
